export const COMMON_FOODS = Object.freeze([
    {
        id: 'preset_latte_intero',
        name: 'Latte Intero',
        category: 'Latticini',
        baseQty: 100,
        unit: 'ml',
        servingUnit: 'bicchiere',
        servingWeight: 200,
        kcal: 64,
        carbs: 4.8,
        pro: 3.3,
        fat: 3.6,
        satFat: 2.3,
        unSatFat: 1.1,
        sugars: 4.8,
        fiber: 0,
        salt: 0.1,
        sodium: 40,
        vitA: 46,
        vitC: 0,
        calcium: 120,
        iron: 0.05
    },
    {
        id: 'preset_uova',
        name: 'Uova Intere',
        category: 'Uova & Proteine',
        baseQty: 100,
        unit: 'g',
        servingUnit: 'uovo',
        servingWeight: 50,
        kcal: 143,
        carbs: 0.7,
        pro: 12.6,
        fat: 9.5,
        satFat: 3.1,
        unSatFat: 5.3,
        sugars: 0.4,
        fiber: 0,
        salt: 0.35,
        sodium: 140,
        vitA: 160,
        vitC: 0,
        calcium: 56,
        iron: 1.75
    },
    {
        id: 'preset_petto_pollo',
        name: 'Petto di Pollo',
        category: 'Carne',
        baseQty: 100,
        unit: 'g',
        servingUnit: 'fetta',
        servingWeight: 120,
        kcal: 110,
        carbs: 0,
        pro: 23.1,
        fat: 1.2,
        satFat: 0.3,
        unSatFat: 0.6,
        sugars: 0,
        fiber: 0,
        salt: 0.16,
        sodium: 65,
        vitA: 6,
        vitC: 0,
        calcium: 15,
        iron: 0.70
    },
    {
        id: 'preset_riso_basmati',
        name: 'Riso Basmati',
        category: 'Cereali & Carboidrati',
        baseQty: 100,
        unit: 'g',
        servingUnit: 'porzione',
        servingWeight: 80,
        kcal: 350,
        carbs: 78.0,
        pro: 8.5,
        fat: 0.6,
        satFat: 0.2,
        unSatFat: 0.3,
        sugars: 0.2,
        fiber: 1.4,
        salt: 0.01,
        sodium: 3,
        vitA: 0,
        vitC: 0,
        calcium: 10,
        iron: 1.20
    },
    {
        id: 'preset_fiocchi_avena',
        name: "Fiocchi d'Avena",
        category: 'Cereali & Carboidrati',
        baseQty: 100,
        unit: 'g',
        servingUnit: 'porzione',
        servingWeight: 50,
        kcal: 375,
        carbs: 60.0,
        pro: 13.5,
        fat: 7.0,
        satFat: 1.2,
        unSatFat: 5.2,
        sugars: 1.1,
        fiber: 10.0,
        salt: 0.02,
        sodium: 6,
        vitA: 0,
        vitC: 0,
        calcium: 52,
        iron: 4.50
    },
    {
        id: 'preset_olio_evo',
        name: 'Olio EVO',
        category: 'Grassi & Olii',
        baseQty: 100,
        unit: 'ml',
        servingUnit: 'cucchiaio',
        servingWeight: 10,
        kcal: 824,
        carbs: 0,
        pro: 0,
        fat: 91.6,
        satFat: 13.8,
        unSatFat: 72.8,
        sugars: 0,
        fiber: 0,
        salt: 0,
        sodium: 0,
        vitA: 0,
        vitC: 0,
        calcium: 1,
        iron: 0.40
    },
    {
        id: 'preset_salmone',
        name: 'Salmone',
        category: 'Pesce',
        baseQty: 100,
        unit: 'g',
        servingUnit: 'filetto',
        servingWeight: 150,
        kcal: 208,
        carbs: 0,
        pro: 20.4,
        fat: 13.4,
        satFat: 3.1,
        unSatFat: 9.3,
        sugars: 0,
        fiber: 0,
        salt: 0.15,
        sodium: 60,
        vitA: 12,
        vitC: 0,
        calcium: 12,
        iron: 0.80
    },
    {
        id: 'preset_pane_integrale',
        name: 'Pane Integrale',
        category: 'Cereali & Carboidrati',
        baseQty: 100,
        unit: 'g',
        servingUnit: 'fetta',
        servingWeight: 40,
        kcal: 247,
        carbs: 41.3,
        pro: 12.0,
        fat: 3.4,
        satFat: 0.7,
        unSatFat: 2.1,
        sugars: 4.3,
        fiber: 6.0,
        salt: 1.10,
        sodium: 450,
        vitA: 0,
        vitC: 0,
        calcium: 107,
        iron: 2.50
    },
    {
        id: 'preset_mela',
        name: 'Mela',
        category: 'Frutta',
        baseQty: 100,
        unit: 'g',
        servingUnit: 'frutto',
        servingWeight: 180,
        kcal: 52,
        carbs: 13.8,
        pro: 0.3,
        fat: 0.2,
        satFat: 0.03,
        unSatFat: 0.1,
        sugars: 10.4,
        fiber: 2.4,
        salt: 0.003,
        sodium: 1,
        vitA: 3,
        vitC: 4.6,
        calcium: 6,
        iron: 0.12
    },
    {
        id: 'preset_banana',
        name: 'Banana',
        category: 'Frutta',
        baseQty: 100,
        unit: 'g',
        servingUnit: 'frutto',
        servingWeight: 120,
        kcal: 89,
        carbs: 22.8,
        pro: 1.1,
        fat: 0.3,
        satFat: 0.1,
        unSatFat: 0.1,
        sugars: 12.2,
        fiber: 2.6,
        salt: 0.003,
        sodium: 1,
        vitA: 3,
        vitC: 8.7,
        calcium: 5,
        iron: 0.26
    }
]);
