export interface MuscleDef {
    id: string;
    name: string;
}

export const MUSCLES: MuscleDef[] = [
    { id: "abductors_right", name: "Abduttore Destro" },
    { id: "abductors_left", name: "Abduttore Sinistro" },
    { id: "abductors", name: "Abduttori (Esterno Coscia)" },
    { id: "abs", name: "Addome (Retto dell'Addome)" },
    { id: "abs_upper", name: "Addominali Alti" },
    { id: "abs_lower", name: "Addominali Bassi (V-Shape)" },
    { id: "adductors_right", name: "Adduttore Destro" },
    { id: "adductors_left", name: "Adduttore Sinistro" },
    { id: "adductors", name: "Adduttori (Interno Coscia)" },
    { id: "forearms", name: "Avambracci" },
    { id: "forearms_right", name: "Avambraccio Destro" },
    { id: "forearms_left", name: "Avambraccio Sinistro" },
    { id: "biceps_right", name: "Bicipite Destro" },
    { id: "biceps_left", name: "Bicipite Sinistro" },
    { id: "biceps", name: "Bicipiti" },
    { id: "brachialis", name: "Brachiale" },
    { id: "biceps_short", name: "Capo Breve del Bicipite" },
    { id: "biceps_short_right", name: "Capo Breve del Bicipite Destro" },
    { id: "biceps_short_left", name: "Capo Breve del Bicipite Sinistro" },
    { id: "triceps_lateral", name: "Capo Laterale del Tricipite" },
    { id: "triceps_lateral_right", name: "Capo Laterale del Tricipite Destro" },
    { id: "triceps_lateral_left", name: "Capo Laterale del Tricipite Sinistro" },
    { id: "biceps_long", name: "Capo Lungo del Bicipite" },
    { id: "biceps_long_right", name: "Capo Lungo del Bicipite Destro" },
    { id: "biceps_long_left", name: "Capo Lungo del Bicipite Sinistro" },
    { id: "triceps_long", name: "Capo Lungo del Tricipite" },
    { id: "triceps_long_right", name: "Capo Lungo del Tricipite Destro" },
    { id: "triceps_long_left", name: "Capo Lungo del Tricipite Sinistro" },
    { id: "triceps_medial", name: "Capo Mediale del Tricipite" },
    { id: "triceps_medial_right", name: "Capo Mediale del Tricipite Destro" },
    { id: "triceps_medial_left", name: "Capo Mediale del Tricipite Sinistro" },
    { id: "core", name: "Core" },
    { id: "delts_front", name: "Deltoide Anteriore" },
    { id: "delts_front_right", name: "Deltoide Anteriore Destro" },
    { id: "delts_front_left", name: "Deltoide Anteriore Sinistro" },
    { id: "delts_side", name: "Deltoide Laterale" },
    { id: "delts_side_right", name: "Deltoide Laterale Destro" },
    { id: "delts_side_left", name: "Deltoide Laterale Sinistro" },
    { id: "delts_rear", name: "Deltoide Posteriore" },
    { id: "delts_rear_right", name: "Deltoide Posteriore Destro" },
    { id: "delts_rear_left", name: "Deltoide Posteriore Sinistro" },
    { id: "back", name: "Dorso" },
    { id: "chest_lower", name: "Fascio Addominale (Petto Basso)" },
    { id: "chest_lower_right", name: "Fascio Addominale Destro" },
    { id: "chest_lower_left", name: "Fascio Addominale Sinistro" },
    { id: "chest_upper", name: "Fascio Clavicolare (Petto Alto)" },
    { id: "chest_upper_right", name: "Fascio Clavicolare Destro" },
    { id: "chest_upper_left", name: "Fascio Clavicolare Sinistro" },
    { id: "hamstrings_right", name: "Femorale Destro" },
    { id: "hamstrings_left", name: "Femorale Sinistro" },
    { id: "hamstrings", name: "Femorali" },
    { id: "hand_flexors_right", name: "Flessori Mano Destra" },
    { id: "hand_flexors_left", name: "Flessori Mano Sinistra" },
    { id: "glutes", name: "Glutei" },
    { id: "glutes_right", name: "Gluteo Destro" },
    { id: "glutes_left", name: "Gluteo Sinistro" },
    { id: "legs_general", name: "Gambe (Generale)" },
    { id: "lats", name: "Gran Dorsale" },
    { id: "lats_right", name: "Gran Dorsale Destro" },
    { id: "lats_left", name: "Gran Dorsale Sinistro" },
    { id: "lower_back", name: "Lombari" },
    { id: "obliques", name: "Obliqui" },
    { id: "chest", name: "Petto" },
    { id: "chest_right", name: "Petto Destro" },
    { id: "chest_left", name: "Petto Sinistro" },
    { id: "calves", name: "Polpacci" },
    { id: "calves_right", name: "Polpaccio Destro" },
    { id: "calves_left", name: "Polpaccio Sinistro" },
    { id: "quads_right", name: "Quadricipite Destro" },
    { id: "quads_left", name: "Quadricipite Sinistro" },
    { id: "quads", name: "Quadricipiti" },
    { id: "rhomboids", name: "Romboidi" },
    { id: "shoulders", name: "Spalle" },
    { id: "traps", name: "Trapezi" },
    { id: "traps_right", name: "Trapezio Destro" },
    { id: "traps_left", name: "Trapezio Sinistro" },
    { id: "triceps_right", name: "Tricipite Destro" },
    { id: "triceps_left", name: "Tricipite Sinistro" },
    { id: "triceps", name: "Tricipiti" },
];

export const GROUP_MAP: Record<string, string[]> = {
    'abductors': ['gluteus-medius-left', 'gluteus-medius-right'],
    'abductors_left': ['gluteus-medius-left'],
    'abductors_right': ['gluteus-medius-right'],
    'abs': ['abs-lower-left', 'abs-lower-right', 'abs-upper-left', 'abs-upper-right'],
    'abs_lower': ['abs-lower-left', 'abs-lower-right'],
    'abs_upper': ['abs-upper-left', 'abs-upper-right'],
    'adductors': ['adductors-left_1', 'adductors-left_2', 'adductors-right_1', 'adductors-right_2'],
    'adductors_left': ['adductors-left_1', 'adductors-left_2'],
    'adductors_right': ['adductors-right_1', 'adductors-right_2'],
    'back': ['lats-lower-left', 'lats-lower-right', 'lats-mid-left', 'lats-mid-right', 'deltoid-rear-left', 'deltoid-rear-right', 'lower-back-erectors-left', 'lower-back-erectors-right', 'lower-back-ql-left', 'lower-back-ql-right', 'nape_1', 'nape_2', 'spine', 'traps-lower-left', 'traps-lower-right', 'traps-mid-left', 'traps-mid-right', 'traps-upper-left', 'traps-upper-right'],
    'biceps': ['biceps-left_1', 'biceps-left_2', 'biceps-left_3', 'biceps-right_1', 'biceps-right_2', 'biceps-right_3'],
    'biceps_left': ['biceps-left_1', 'biceps-left_2', 'biceps-left_3'],
    'biceps_right': ['biceps-right_1', 'biceps-right_2', 'biceps-right_3'],
    'biceps_long': ['biceps-left_1', 'biceps-left_2', 'biceps-left_3', 'biceps-right_1', 'biceps-right_2', 'biceps-right_3'],
    'biceps_long_left': ['biceps-left_1', 'biceps-left_2', 'biceps-left_3'],
    'biceps_long_right': ['biceps-right_1', 'biceps-right_2', 'biceps-right_3'],
    'biceps_short': ['biceps-left_1', 'biceps-left_2', 'biceps-left_3', 'biceps-right_1', 'biceps-right_2', 'biceps-right_3'],
    'biceps_short_left': ['biceps-left_1', 'biceps-left_2', 'biceps-left_3'],
    'biceps_short_right': ['biceps-right_1', 'biceps-right_2', 'biceps-right_3'],
    'brachialis': ['biceps-left_1', 'biceps-left_2', 'biceps-left_3', 'biceps-right_1', 'biceps-right_2', 'biceps-right_3'],
    'calves': ['calves-gastroc-lateral-left', 'calves-gastroc-lateral-right', 'calves-gastroc-medial-left', 'calves-gastroc-medial-right', 'calves-soleus-left', 'calves-soleus-right'],
    'calves_left': ['calves-gastroc-lateral-left', 'calves-gastroc-medial-left', 'calves-soleus-left'],
    'calves_right': ['calves-gastroc-lateral-right', 'calves-gastroc-medial-right', 'calves-soleus-right'],
    'chest': ['chest-lower-left', 'chest-lower-right', 'chest-upper-left', 'chest-upper-right'],
    'chest_left': ['chest-lower-left', 'chest-upper-left'],
    'chest_right': ['chest-lower-right', 'chest-upper-right'],
    'chest_lower': ['chest-lower-left', 'chest-lower-right'],
    'chest_lower_left': ['chest-lower-left'],
    'chest_lower_right': ['chest-lower-right'],
    'chest_upper': ['chest-upper-left', 'chest-upper-right'],
    'chest_upper_left': ['chest-upper-left'],
    'chest_upper_right': ['chest-upper-right'],
    'core': ['abs-lower-left', 'abs-lower-right', 'abs-upper-left', 'abs-upper-right', 'lower-back-erectors-left', 'lower-back-erectors-right', 'lower-back-ql-left', 'lower-back-ql-right', 'obliques-left_1', 'obliques-left_2', 'obliques-left_3', 'obliques-right_1', 'obliques-right_2', 'obliques-right_3'],
    'delts_front': ['shoulder-front-left_1', 'shoulder-front-left_2', 'shoulder-front-right_1', 'shoulder-front-right_2'],
    'delts_front_left': ['shoulder-front-left_1', 'shoulder-front-left_2'],
    'delts_front_right': ['shoulder-front-right_1', 'shoulder-front-right_2'],
    'delts_rear': ['deltoid-rear-left', 'deltoid-rear-right'],
    'delts_rear_left': ['deltoid-rear-left'],
    'delts_rear_right': ['deltoid-rear-right'],
    'delts_side': ['shoulder-side-left_1', 'shoulder-side-left_2', 'shoulder-side-right_1', 'shoulder-side-right_2', 'deltoid-side-back-left', 'deltoid-side-back-right'],
    'delts_side_left': ['shoulder-side-left_1', 'shoulder-side-left_2', 'deltoid-side-back-left'],
    'delts_side_right': ['shoulder-side-right_1', 'shoulder-side-right_2', 'deltoid-side-back-right'],
    'forearms': ['forearm-extensors-left', 'forearm-extensors-right', 'forearm-flexors-left', 'forearm-flexors-right', 'forearm-left_1', 'forearm-left_2', 'forearm-right_1', 'forearm-right_2', 'hand-left', 'hand-right'],
    'forearms_left': ['forearm-extensors-left', 'forearm-flexors-left', 'forearm-left_1', 'forearm-left_2', 'hand-left'],
    'forearms_right': ['forearm-extensors-right', 'forearm-flexors-right', 'forearm-right_1', 'forearm-right_2', 'hand-right'],
    'glutes': ['gluteus-maximus-left', 'gluteus-maximus-right', 'gluteus-medius-left', 'gluteus-medius-right'],
    'glutes_left': ['gluteus-maximus-left', 'gluteus-medius-left'],
    'glutes_right': ['gluteus-maximus-right', 'gluteus-medius-right'],
    'hamstrings': ['hamstrings-lateral-left', 'hamstrings-lateral-right', 'hamstrings-medial-left', 'hamstrings-medial-right'],
    'hamstrings_left': ['hamstrings-lateral-left', 'hamstrings-medial-left'],
    'hamstrings_right': ['hamstrings-lateral-right', 'hamstrings-medial-right'],
    'hand_flexors_left': ['forearm-flexors-left', 'hand-left'],
    'hand_flexors_right': ['forearm-flexors-right', 'hand-right'],
    'lats': ['lats-lower-left', 'lats-lower-right', 'lats-mid-left', 'lats-mid-right'],
    'lats_left': ['lats-lower-left', 'lats-mid-left'],
    'lats_right': ['lats-lower-right', 'lats-mid-right'],
    'legs_general': ['quads-left_1', 'quads-left_2', 'quads-left_3', 'quads-right_1', 'quads-right_2', 'quads-right_3', 'hamstrings-lateral-left', 'hamstrings-medial-left', 'hamstrings-lateral-right', 'hamstrings-medial-right', 'gluteus-maximus-left', 'gluteus-medius-left', 'gluteus-maximus-right', 'gluteus-medius-right', 'calves-gastroc-lateral-left', 'calves-gastroc-medial-left', 'calves-soleus-left', 'calves-gastroc-lateral-right', 'calves-gastroc-medial-right', 'calves-soleus-right', 'adductors-left_1', 'adductors-left_2', 'adductors-right_1', 'adductors-right_2'],
    'lower_back': ['lower-back-erectors-left', 'lower-back-erectors-right', 'lower-back-ql-left', 'lower-back-ql-right', 'spine'],
    'obliques': ['obliques-left_1', 'obliques-left_2', 'obliques-left_3', 'obliques-right_1', 'obliques-right_2', 'obliques-right_3', 'serratus-anterior-left_1', 'serratus-anterior-left_2', 'serratus-anterior-left_3', 'serratus-anterior-left_4', 'serratus-anterior-right_1', 'serratus-anterior-right_2', 'serratus-anterior-right_3', 'serratus-anterior-right_4'],
    'quads': ['quads-left_1', 'quads-left_2', 'quads-left_3', 'quads-right_1', 'quads-right_2', 'quads-right_3'],
    'quads_left': ['quads-left_1', 'quads-left_2', 'quads-left_3'],
    'quads_right': ['quads-right_1', 'quads-right_2', 'quads-right_3'],
    'rhomboids': ['traps-mid-left', 'traps-mid-right'],
    'shoulders': ['deltoid-rear-left', 'deltoid-rear-right', 'shoulder-front-left_1', 'shoulder-front-left_2', 'shoulder-front-right_1', 'shoulder-front-right_2', 'shoulder-side-left_1', 'shoulder-side-left_2', 'shoulder-side-right_1', 'shoulder-side-right_2', 'deltoid-side-back-left', 'deltoid-side-back-right'],
    'traps': ['nape_1', 'nape_2', 'traps-lower-left', 'traps-lower-right', 'traps-mid-left', 'traps-mid-right', 'traps-upper-left', 'traps-upper-right'],
    'traps_left': ['traps-upper-left', 'traps-mid-left', 'traps-lower-left', 'nape_1'],
    'traps_right': ['traps-upper-right', 'traps-mid-right', 'traps-lower-right', 'nape_2'],
    'triceps': ['triceps-lateral-left', 'triceps-lateral-right', 'triceps-long-left', 'triceps-long-right'],
    'triceps_left': ['triceps-lateral-left', 'triceps-long-left'],
    'triceps_right': ['triceps-lateral-right', 'triceps-long-right'],
    'triceps_lateral': ['triceps-lateral-left', 'triceps-lateral-right'],
    'triceps_lateral_left': ['triceps-lateral-left'],
    'triceps_lateral_right': ['triceps-lateral-right'],
    'triceps_long': ['triceps-long-left', 'triceps-long-right'],
    'triceps_long_left': ['triceps-long-left'],
    'triceps_long_right': ['triceps-long-right'],
    'triceps_medial': ['triceps-long-left', 'triceps-long-right'],
    'triceps_medial_left': ['triceps-long-left'],
    'triceps_medial_right': ['triceps-long-right'],
};
