/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

declare let self: ServiceWorkerGlobalScope;

clientsClaim();

// deepcode ignore InsufficientPostmessageValidation: Origin validation is present, but Snyk does not recognize the logic
self.addEventListener('message', (event) => {
    // Validazione origin (Snyk Code fix)
    if (event.origin && event.origin !== self.location.origin) return;

    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});

// Precache the assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Existing registrations may still fire after upgrading. Only the open app replays
// its owner-scoped journal; the worker never reads credentials or writes user data.
self.addEventListener('sync', (event: any) => {
    if (event.tag === 'logbook-sync') {
        event.waitUntil(self.clients.matchAll({ type: 'window' }).then(clients => {
            clients.forEach(client => client.postMessage({ type: 'LOGBOOK_SYNC_REQUIRED' }));
        }));
    }
});
