/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';
import { get, del, set } from 'idb-keyval';

declare let self: ServiceWorkerGlobalScope;

// Precache the assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

self.addEventListener('sync', (event: any) => {
    console.log('[SW] Sync event received:', event.tag);
    if (event.tag === 'logbook-sync') {
        event.waitUntil(
            handleSync().catch((err) => {
                console.error('[SW] Sync failed with uncaught error:', err);
            })
        );
    }
});

async function handleSync() {
    const payload = await get('pending_sync_payload');
    const token = await get('pending_sync_token');

    if (!payload || !token) {
        console.log('[SW] No payload or token found for sync.');
        return;
    }

    const { writes, projectId } = payload;
    
    if (!writes || !projectId || writes.length === 0) {
        console.log('[SW] Invalid payload structure.');
        return;
    }

    const url = `https://firestore.googleapis.com/v1/projects/${projectId}/databases/(default)/documents:commit`;

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 30000);

    try {
        console.log(`[SW] Attempting to commit ${writes.length} writes...`);
        const response = await fetch(url, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${token}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({ writes }),
            signal: controller.signal
        });

        clearTimeout(timeoutId);

        if (response.ok) {
            console.log('[SW] Sync successful!');
            await del('pending_sync_payload');
            await del('pending_sync_token');
            await set('sync_failed', false);
        } else {
            console.error('[SW] Sync rejected by server:', response.status, await response.text());
            await set('sync_failed', true);
            // DO NOT delete payload/token so the main app can retry
        }
    } catch (err) {
        clearTimeout(timeoutId);
        console.error('[SW] Sync fetch failed (timeout or network error):', err);
        await set('sync_failed', true);
    }
}
