/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { get, del, set } from 'idb-keyval';

declare let self: ServiceWorkerGlobalScope;

clientsClaim();

self.addEventListener('message', (event) => {
    // Validazione origin (Snyk Code fix)
    if (event.origin && event.origin !== self.location.origin) return;

    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});

// Precache the assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

const IS_DEV = import.meta.env?.DEV || false;
const logger = {
    log: (...args: any[]) => IS_DEV && console.log('[SW]', ...args),
    error: (...args: any[]) => console.error('[SW]', ...args),
};

self.addEventListener('sync', (event: any) => {
    logger.log('Sync event received:', event.tag);
    if (event.tag === 'logbook-sync') {
        event.waitUntil(
            handleSync().catch((err) => {
                logger.error('Sync failed with uncaught error:', err);
            })
        );
    }
});

function sleep(ms: number) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

async function handleSync() {
    const payload = await get('pending_sync_payload');
    const token = await get('pending_sync_token');

    if (!payload || !token) {
        logger.log('No payload or token found for sync.');
        return;
    }

    const { writes, projectId } = payload;
    
    if (!writes || !projectId || writes.length === 0) {
        logger.log('Invalid payload structure.');
        return;
    }

    const url = `https://firestore.googleapis.com/v1/projects/${projectId}/databases/(default)/documents:commit`;
    const MAX_RETRIES = 3;
    let attempt = 0;

    while (attempt < MAX_RETRIES) {
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 30000);

        try {
            logger.log(`Attempting to commit ${writes.length} writes (Attempt ${attempt + 1})...`);
            const response = await fetch(url, {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${token}`,
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ writes }),
                signal: controller.signal
            });

            clearTimeout(timeoutId);

            if (response.ok) {
                logger.log('Sync successful!');
                await del('pending_sync_payload');
                await del('pending_sync_token');
                await set('sync_failed', false);
                return;
            }

            if (response.status === 401) {
                logger.error('Sync rejected: 401 Unauthorized (Token expired)');
                await set('sync_failed', true);
                return;
            }

            if (response.status >= 500) {
                logger.error(`Server error ${response.status}. Retrying...`);
                attempt++;
                await sleep(Math.pow(2, attempt) * 1000);
                continue;
            }

            logger.error('Sync rejected by server:', response.status, await response.text());
            await set('sync_failed', true);
            return;

        } catch (err) {
            clearTimeout(timeoutId);
            logger.error('Sync fetch failed (timeout or network error):', err);
            attempt++;
            if (attempt >= MAX_RETRIES) {
                await set('sync_failed', true);
                return;
            }
            await sleep(Math.pow(2, attempt) * 1000);
        }
    }
    
    await set('sync_failed', true);
}
